version: '3.8'

services:
  photo-processing-web:
    build:
      context: ./photo-processing-server
      dockerfile: Dockerfile.web
    ports:
      - "8090:8080"
    volumes:
      - ./data/photos:/app/data/photos:z
      - ./data/processed:/app/data/processed:z
      - ./data/temp:/app/data/temp:z
      - ./uploads:/app/uploads:z
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8090}
      - API_TOKEN=${API_TOKEN:-}
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  photos:
  processed:
  temp:
  redis-data: